# Generated by Django 5.2 on 2025-06-09 07:00

import recipe_app.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=recipe_app.storage_backends.SupabaseMediaStorage(), upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=recipe_app.storage_backends.SupabaseMediaStorage(), upload_to='recipes/'),
        ),
    ]
